[tool.ruff]
lint.select = ["D", "E", "F", "RUF", "W"]
line-length = 88

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 88

[tool.ruff.format]
docstring-code-format = true
